server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: cem-gateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: "http://localhost:3000,http://localhost:3001,http://localhost:8080,https://localhost:8080,https://localhost:8081,https://localhost:8082,https://localhost:8083,https://localhost:8084,https://cem.vercel.app,https://api-cem.azurewebsites.net"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: device-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/device/**
          filters:
            - StripPrefix=2
        - id: contract-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/contract/**
          filters:
            - StripPrefix=2
        - id: spareparts-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/spare-parts/**
          filters:
            - StripPrefix=1
        - id: suppliers-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/suppliers/**
          filters:
            - StripPrefix=1
        - id: supplier-device-types-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/supplier-device-types/**
          filters:
            - StripPrefix=1
        - id: spare-part-inventory-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/spare-part-inventory/**
          filters:
            - StripPrefix=2
        - id: spare-part-inventory-all-with-inventory
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/spare-part-inventory/all-with-inventory/**
          filters:
            - StripPrefix=3

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs
        name: Gateway
      - url: /api/auth/api-docs
        name: Authentication Service
      - url: /api/customer/api-docs
        name: Customer Service
      - url: /api/device/api-docs
        name: Device Service
      - url: /api/contract/api-docs
        name: Contract Service
      - url: /api/spare-parts/api-docs
        name: Spare Parts Service 