spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cem_contract_prod}
    username: ${DB_USERNAME:cem_user}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://auth.cem-system.com}
          jwk-set-uri: ${JWT_JWK_SET_URI:https://auth.cem-system.com/.well-known/jwks.json}

  cache:
    type: redis
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Digital Signature Configuration
app:
  signature:
    default-certificate-id: ${DEFAULT_CERTIFICATE_ID:1}
    timestamp-url: ${TIMESTAMP_URL:http://timestamp.digicert.com}
    enable-timestamp: ${ENABLE_TIMESTAMP:true}
    signature-timeout-seconds: ${SIGNATURE_TIMEOUT:30}
    verification-cache-ttl: ${VERIFICATION_CACHE_TTL:3600}
    max-signature-size-mb: ${MAX_SIGNATURE_SIZE:10}
    allowed-signature-algorithms:
      - SHA256_WITH_RSA
      - SHA256_WITH_ECDSA
      - SHA384_WITH_RSA
      - SHA512_WITH_RSA
      - ED25519
    pdf:
      max-file-size-mb: ${MAX_PDF_SIZE:100}
      compression-level: ${PDF_COMPRESSION:6}
      enable-validation: ${PDF_VALIDATION:true}
    certificate:
      auto-create-self-signed: ${AUTO_CREATE_CERT:false}
      key-size: ${CERT_KEY_SIZE:2048}
      validity-years: ${CERT_VALIDITY_YEARS:2}
      cleanup-expired: ${CLEANUP_EXPIRED_CERTS:true}

# Google Drive Configuration
google:
  drive:
    credentials-file: ${GOOGLE_CREDENTIALS_FILE:/etc/secrets/google-credentials.json}
    application-name: ${GOOGLE_APP_NAME:CEM-Contract-System}
    folder-id: ${GOOGLE_DRIVE_FOLDER_ID:}
    timeout-seconds: ${GOOGLE_TIMEOUT:60}
    retry-attempts: ${GOOGLE_RETRY:3}
    chunk-size-mb: ${GOOGLE_CHUNK_SIZE:32}

# Logging Configuration
logging:
  level:
    com.g47.cem.cemcontract: INFO
    com.g47.cem.cemcontract.service.DigitalSignatureService: INFO
    com.g47.cem.cemcontract.controller.ContractController: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:/var/log/cem-contract/application.log}
    max-size: 100MB
    max-history: 30

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: cem-contract
      environment: production

# Security Headers
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1/contracts
  compression:
    enabled: true
    mime-types: application/json,text/plain,text/css,application/javascript
    min-response-size: 1024
  http2:
    enabled: true
  ssl:
    enabled: ${SSL_ENABLED:true}
    key-store: ${SSL_KEYSTORE:/etc/ssl/keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers: 
      - TLS_AES_256_GCM_SHA384
      - TLS_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

# Circuit Breaker and Resilience
resilience4j:
  circuitbreaker:
    instances:
      digitalSignature:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 100
        ring-buffer-size-in-half-open-state: 10
        wait-duration-in-open-state: 60s
        failure-rate-threshold: 50
        record-exceptions:
          - java.lang.Exception
      googleDrive:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 50
        ring-buffer-size-in-half-open-state: 5
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 60

  retry:
    instances:
      digitalSignature:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
      googleDrive:
        max-attempts: 3
        wait-duration: 2s
        exponential-backoff-multiplier: 2

  timelimiter:
    instances:
      digitalSignature:
        timeout-duration: 30s
      googleDrive:
        timeout-duration: 60s

# Thread Pool Configuration  
  task:
    execution:
      pool:
        core-size: 8
        max-size: 20
        queue-capacity: 100
        keep-alive: 60s
      thread-name-prefix: cem-task-
    scheduling:
      pool:
        size: 5

  # Additional Production Settings  
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://cem-frontend.com,https://app.cem-system.com}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

  rate-limiting:
    enabled: ${RATE_LIMITING_ENABLED:true}
    requests-per-minute: ${RATE_LIMIT_RPM:100}
    burst-capacity: ${RATE_LIMIT_BURST:150}

  audit:
    enabled: ${AUDIT_ENABLED:true}
    log-level: INFO
    include-request-body: ${AUDIT_INCLUDE_BODY:false}
    include-response-body: ${AUDIT_INCLUDE_RESPONSE:false}
    max-body-size: 1024

  monitoring:
    signature-performance:
      enabled: true
      log-slow-operations: true
      slow-threshold-ms: 5000
    
  cleanup:
    temp-files:
      enabled: true
      max-age-hours: 24
      cleanup-interval: 1h
    
    old-signatures:
      enabled: ${CLEANUP_OLD_SIGNATURES:false}
      retention-years: ${SIGNATURE_RETENTION_YEARS:7}
      cleanup-interval: 24h 