server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: cem-authentication-service
  main:
    allow-bean-definition-overriding: true
  
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  datasource:
    url: jdbc:postgresql://ep-royal-bird-a1m9xsdr.ap-southeast-1.aws.neon.tech:5432/CEM_DB?sslmode=require
    username: default
    password: USIBWX1Y4Lui
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: HikariPool-AUTH
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  flyway:
    enabled: false
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/api/auth
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhdatcems@gmail.com
    password: e a o v w x v c y h r p r t k i
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

eureka:
  client:
    enabled: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266546A576E5A7234753778214125442A472D4B6150645367566B5970}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  health:
    mail:
      enabled: false
  prometheus:
    metrics:
      export:
        enabled: true

# Logging
logging:
  level:
    com.g47.cem: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/auth-service.log

# Custom Application Properties
app:
  cors:
    allowedOrigins: "http://localhost:3000,http://localhost:3001,http://localhost:8080,https://localhost:8080,https://localhost:8081,https://localhost:8082,https://localhost:8083,https://localhost:8084,https://cem.vercel.app,https://api-cem.azurewebsites.net"
  security:
    permitAll: "/api-docs/**,/swagger-ui/**,/swagger-ui.html,/v1/auth/login,/v1/auth/refresh-token,/v1/auth/forgot-password,/v1/auth/reset-password,/actuator/health"
  admin:
    password: "Abc123!@"
  reset-password:
    url: "http://localhost:3000/reset-password"